import glob from 'fast-glob'
import * as fs from 'fs'
import { normalize } from 'node:path'
import { fileURLToPath } from 'node:url'
import * as path from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const ROOT_DIR = path.resolve(__dirname, '../src')

const INDEX_FILE_NAME = 'index.ts'

const shouldIncludeFile: (absolutePath: string) => boolean = (p) => {
  if (p === 'Internal/helpers.ts') return false
  return true
}

const GENERATED_HEADER = '// @sort-all (generated by `npm run re-index`)\n'

async function run() {
  console.log(`\nScanning: ${ROOT_DIR}\n`)

  const allFiles = await getAllFiles(ROOT_DIR)
  if (allFiles.length === 0) {
    console.log('No files found.')
    return
  }

  const sorted = [...allFiles].sort()

  const exportLines = sorted.map((file) => {
    const importPath = normalizePath(
      path.relative(ROOT_DIR, file).replace(/\.ts$/, ''),
    )
    return { dir: path.dirname(file), line: `export * from './${importPath}'` }
  })

  const grouped: string[] = []
  let lastDir: string | null = null
  for (const { dir, line } of exportLines) {
    if (lastDir !== null && dir !== lastDir) grouped.push('')
    grouped.push(line)
    lastDir = dir
  }

  const lines: string[] = [
    GENERATED_HEADER,
    ...grouped,
    '', // trailing newline
  ]

  const indexPath = path.join(ROOT_DIR, INDEX_FILE_NAME)
  const newContent = lines.join('\n')

  const existing = fs.existsSync(indexPath)
    ? fs.readFileSync(indexPath, 'utf8')
    : null

  if (existing === newContent) {
    console.log(`  ✓ unchanged  ${INDEX_FILE_NAME}`)
  } else {
    fs.writeFileSync(indexPath, newContent, 'utf8')
    console.log(`  ✍  updated   ${INDEX_FILE_NAME}`)
  }

  console.log(`\nDone — exported ${sorted.length} file${sorted.length === 1 ? '' : 's'}.\n`)
}

async function getAllFiles(dir: string) {
  const files = await glob('**/*.ts', {
    cwd: dir,
    absolute: true,
    onlyFiles: true,
    ignore: ['**/*.d.ts', '**/index.ts', '**/' + INDEX_FILE_NAME],
  })

  return files.filter((f) => shouldIncludeFile(path.relative(ROOT_DIR, f)))
}

export const normalizePath = (file: string) => normalize(file).replace(/\\/g, '/')

run()
